//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int NhanVienID { get; set; }
        public string TenNhanVien { get; set; }
        public string VaiTro { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
    }
}
